# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='rate',
            field=models.IntegerField(blank=True),
        ),
    ]
