# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20170926_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
