# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0005_remove_trip_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='places',
            field=models.ManyToManyField(blank=True, to='places.Place'),
        ),
    ]
