# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20170922_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
