# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_auto_20170925_2001'),
        ('places', '0003_auto_20170925_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='place',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='place',
            name='hours',
            field=models.ManyToManyField(to='hours.OpeningHours'),
        ),
        migrations.AddField(
            model_name='place',
            name='street',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
