# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20170926_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('audioURL', models.URLField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
            ],
            options={
                'ordering': ('weekday', 'opening_hour'),
            },
        ),
        migrations.RemoveField(
            model_name='place',
            name='guide',
        ),
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together=set([('weekday', 'opening_hour', 'closing_hour')]),
        ),
        migrations.AddField(
            model_name='guide',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='places.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='hours',
            field=models.ManyToManyField(blank=True, to='places.OpeningHour'),
        ),
    ]
