# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20170927_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghour',
            name='closing_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='opening_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
