# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20170928_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='rate',
        ),
    ]
