# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_place_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='text',
            field=models.TextField(default='Descirption'),
            preserve_default=False,
        ),
    ]
