# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_guide_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='place',
            name='opening_time',
        ),
    ]
