# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20171007_1332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinghour',
            unique_together=set([]),
        ),
    ]
