# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_auto_20170925_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningHours',
            new_name='OpeningHour',
        ),
    ]
